name: Lint Swift Files
on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"
jobs:
  swiftlint:
    if: '!github.event.pull_request.merged'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint 0.65.0
        uses: docker://ghcr.io/realm/swiftlint:0.65.0
        with:
          args: --strict
